### ISSUE TITLE
Constrained min. problem

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#10]
This is my code to solve the optimal portfolio weights, but it gives me an error saying that the tuple, which is `con` is not callable. 

`f = lambda w: Sigma_p`
`con = ({'type' : 'eq',`
              `'fun'  : lambda w: (w.T @ mu) - 0.01},`
            `{'type' : 'eq',`
              `'fun'  : lambda w: (w.T @ np.full((5,1),1)) - 1})`

`w0 = np.full((5,1),0.2)`
`wstar = scipy.optimize.fmin_slsqp(f, w0, f_eqcons=con, acc=1e-09, iprint=2)`
`wstar`

**Comment by jmbejara** [comment]
Take a look at the documentation here: https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.optimize.fmin_slsqp.html

You can supply the constrains using `eqcons` or `f_eqcons`. The first requires a list of scalar-valued functions representing the constraints. It should be supplied as a list of functions. The second requires that you write a single, vector-valued function that represents the constraints. It should be supplied as a single callable. You can use either one you choose. 

To understand the error, consider the following code:


```
a = ()

def hi():
    print('hi')

def fun(c):
    c()
```

The function `fun` takes a callable. If I supply `a`, I get the same error you're describing. If I supply `hi`, it works fine.

![image](https://user-images.githubusercontent.com/3770323/38513879-2bd25b86-3bf5-11e8-8f8c-327a3de76767.png)

**Comment by afgong** [comment]
When you mean "callable" in your example, do you mean that c() represents a function? So if we're phrasing the problem differently, a is an empty list, which doesn't correspond to a function. However hi() is a function, so we can "call" it?

Thanks!

**Comment by jmbejara** [comment]
`c` in `fun` represents a callable (typically a function). `a` here is a tuple. `hi` is a function. `hi()` is not a function, but whatever the function `hi` returns. (`hi` doesn't return anything.) The `()` on `hi()` is what causes `hi` to be "called."
