### ISSUE TITLE
My graph looks like a straight line...

### ISSUE THREAD

**Issue by alykhanb96** [jmbejara/comp-econ-sp18#11]
```
# TODO
import numpy
mean_grid = numpy.linspace(-.01, 2, num = 100, endpoint = True)
#print(mean_grid)
mg = mean_grid
var_needed = np.empty(100)
j = 0
for i in mg:
  mup = i
  cons = [lambda f: (f.T @ mu) - mup, lambda f: (f.T @ np.full((5,1),1)) - 1]
  var = scipy.optimize.fmin_slsqp(lambda f: f.T@sigma@f, w, eqcons  = cons)
  var_needed[j] = np.amin(var)
  j= j+1
print(var_needed)
plt.plot(var_needed, mean_grid)


plt.xlabel('Portfolio Return Variance')
plt.ylabel('Mean Portfolio Return')
```
returns a graph with a straight line...
please help

**Comment by conniexu75** [comment]
are you using the rets dataset? I had this problem when I was using prices

**Comment by alykhanb96** [comment]
@conniexu75 
I think so. Do you mean to calculate sigma initially? 
```
u= np.mean(rets, axis= 0)
mu
sigma = np.cov(rets, rowvar = False)
sigma
```
Are we supposed to use rets somewhere else as well?

**Comment by conniexu75** [comment]
ohh yeah that's what I meant, nevermind

**Comment by jmbejara** [comment]
The line involving `np.amin(var)` appears to be the error. The output of `scipy.optimize.fmin_slsqp` is the portfolio weights.  You need to calculate the variance associated with the optimal weights after you've solved for the optimal weights.

**Comment by alykhanb96** [comment]
thanks!

**Comment by jmbejara** [comment]
Additionally, you could use the `full_output` toggle and then you could get the value of the objective directly from the optimizer without having to recompute it. Check out the documentation here: https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.optimize.fmin_slsqp.html

You're welcome! Let me know if you have any other questions.
