### ISSUE TITLE
A couple dumb interpretation-of-question questions

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#14]
1) For question 10 in the euro2012 homework, does filter mean keep or remove?
2) For question 14 of same, should we also keep the 'Team' column or only the shooting-accuracy one?

**Comment by jmbejara** [comment]
1. I just want you to create a view (or copy of) a subset of the data set that only shows teams that scored more than 6 goals. In this case, you can just print it to the screen.

2.  Show the shooting accuracy and the team name.

(BTW, I'm updating the HW to be more clear. I'll push the changes soon.)
