### ISSUE TITLE
type of quandle problems

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#15]
The description of problem 2 reuses "find the data from the FRED for Real Gross Domestic Product in the US" instead of saying "find the data from the FRED for US Unemployment rate time series."

I'm also not sure that the title is enough information to identify which unemployment series you want. Long term? Short term?

**Comment by jmbejara** [comment]
I've updated the HW to fix this. I'm looking for the civilian unemployment rate (not seasonally adjusted).

**Comment by afgong** [comment]
In Quandl, there is an option to view the data as "No Transform", "Change", "% Change", and "Cumulative". Should we assume that the data we import into Python and display as a plot is "No Transform"?

**Comment by jmbejara** [comment]
Yeah. These can be convenient at times. But for the assignment,  just use the default option - - - no transform.
