### ISSUE TITLE
Occupations

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#17]
Sorry, I should've asked this in class when we were reviewing the exercise together, but for question 1.5, when it asks us to find the number of observations in the dataset, could we use `occupations.size`? It returns 3772, which is equal to 943*4. I was thinking of "observations" as the number of elements in the dataset. Thank you!!!!

**Comment by jmbejara** [comment]
No worries! `size` is a different measure. To me, an observation is each user. For each observation, we ask a user about their occupation, age, etc. Thus, in this data set, each row is an observation and each column is a different "variable." Check out the concept of "tidy data".

 - http://vita.had.co.nz/papers/tidy-data.html
 - https://en.wikipedia.org/wiki/Tidy_data

**Comment by alykhanb96** [comment]
Is occupations due with homework 2?
Thanks!

**Comment by jmbejara** [comment]
No. The occupations exercises are not due. They're just there to help learn the material.

**Comment by alykhanb96** [comment]
Thanks!
