### ISSUE TITLE
Proper Quandl Links

### ISSUE THREAD

**Issue by benpicker** [jmbejara/comp-econ-sp18#19]
Can you post the links to the specific  quandl data sets you want us to use? I have found 4 separate GDP files and don't know which one to use.

**Comment by jmbejara** [comment]
The assignment should give you enough detail to narrow down the one that you need. 

> On Quandl, find the data from the Federal Reserve Bank of St Louis (from the project called "Federal Reserve Economic Data" or "FRED") for Real Gross Domestic Product in the US. 

Have you found multiple that fit this description? If so, let me know. 

Hope this helps!

**Comment by benpicker** [comment]
Yeah sure, I can provide examples. Other members in my group had further additional ones (I'm waiting on them for the codes). 

GDP: 
- GDPCA
- GDPC1

M2:
- MYAGM2USM052N
- M2

If it was as simple as "click the first google link" that would be fine too. But for instance, one of my groupmates went to quandl's site and searched within it and this yields different results than Google.

**Comment by jmbejara** [comment]
GDPCA and GDPC1 are the same data, except they are given at different frequencies (annual vs quarterly). As for M2 and MYAGM2USM052N, they are the same except that one is seasonally adjusted and the other is not. For the purposes of this exercise, feel free to use either one for both cases.

If you wanted to dig into the data and learn more about all the various measures, that'd be great. I don't actually know too much about the various subtleties between some of the measures available on FRED. For this assignment, I'm not looking for anything more complicated than the most popular time series measures as listed in the documentation for FRED on Quandl. This should help: https://www.quandl.com/data/FRED-Federal-Reserve-Economic-Data/documentation/data-organization
