### ISSUE TITLE
creating_reading_writing problem 5-- wrong data?

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#20]
When I download the zipped file from the link indicated, the file most similar to described is 1) a microsoft csv, not an xls file 2) titled Pregnant_Women_Participating with underscores and 3) has different data rows and columns. What am I missing?

**Comment by arielgoldszmidt** [comment]
I believe this link works to download the data as an XLS: [https://www.kaggle.com/jpmiller/publicassistance/downloads/xls_files_all.zip/2](https://www.kaggle.com/jpmiller/publicassistance/downloads/xls_files_all.zip/2)

**Comment by Jacob-Bishop** [comment]
Yep, that works.
