### ISSUE TITLE
problem with latex and creating_reading_writing

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#21]
I'm getting a 500 : Internal Server Error with the text below when I try to save creating_reading_writing as a pdf. I can still save other documents to pdf. Any idea what might be going wrong?

nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99998 (MiKTeX 2.9.6400 64-bit)
entering extended mode
("C:/Users/Jacob Bishop/Documents/Github/comp-econ-sp18/HW/hw-03/notebook.tex"
LaTeX2e <2017-04-15>
Babel <3.12> and hyphenation patterns for 73 language(s) loaded.
("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex\latex\base\size11.clo"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\fontenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.def")
("C:\Program Files\MiKTeX 2.9\tex\latex\lm\t1lmr.fd"))
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\mathpazo.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\graphics-cfg\graph
ics.cfg") ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-def\xetex.def")))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\caption.st
y"
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\caption3.s
ty"))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\adjustbo
x.sty" ("C:\Program Files\MiKTeX 2.9\tex\latex\xkeyval\xkeyval.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkeyval.tex"
("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkvutils.tex")))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\adjcalc.
sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\trimclip
.sty"
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\collectbox\collect
box.sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\tc-xetex
.def"))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\ifoddpage\ifoddpag
e.sty") ("C:\Program Files\MiKTeX 2.9\tex\latex\ltxmisc\varwidth.sty"))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\xcolor\xcolor.sty"

("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\graphics-cfg\color
.cfg")) ("C:\Program Files\MiKTeX 2.9\tex\latex\tools\enumerate.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\xelatex\xetexconfig\geom
etry.cfg")) ("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amssymb.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amsfonts.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\textcomp.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.def"))
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\upquote\upquote.st
y") ("C:\Program Files\MiKTeX 2.9\tex\latex\eurosym\eurosym.sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\ucs.sty"
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\uni-global.def
")) ("C:\Program Files\MiKTeX 2.9\tex\latex\base\inputenc.sty"

Package inputenc Warning: inputenc package ignored with utf8 based engines.

)
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\fancyvrb\fancyvrb.
sty"
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)) ("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\grffile.st
y" ("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ltxcmds.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\infwarerr.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\etexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty"))))
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.sty")

Package grffile Warning: \Gread@QTm of xetex.def not found on input line 259.

Package grffile Warning: Unsupported \Gread@eps not patched on input line 303.

) ("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\hyperref.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\hobsub-hyperref.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\hobsub-generic.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\auxhook.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\pd1enc.def")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\00miktex\hyperref.
cfg") ("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\url\url.sty"
))

Package hyperref Message: Driver (autodetected): hxetex.

("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\hxetex.def"
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\puenc.def")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\stringenc.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\rerunfilecheck.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\tools\longtable.sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\booktabs\booktabs.
sty")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\enumitem\enumitem.
sty") ("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\ulem\ulem.st
y")
No file notebook.aux.
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1cmr.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\t1ppl.fd")
("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\ltcaption.
sty")
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

("C:\Users\Jacob Bishop\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\ucsencs.def")
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\nameref.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\gettitlestring.sty"))

Package hyperref Warning: Rerun to get /PageLabels entry.

("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\ot1ppl.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\omlzplm.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\omszplm.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\omxzplm.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\psnfss\ot1zplm.fd")

LaTeX Warning: No \author given.

("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\se-ascii-print.def")
("C:\Program Files\MiKTeX 2.9\tex\latex\lm\t1lmtt.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\lm\ts1lmtt.fd")

LaTeX Warning: File `https://i.imgur.com/Ax3pp2A.png' not found on input line 3
12.

! Unable to load picture or PDF file 'https://i.imgur.com/Ax3pp2A.png'.
<to be read again> 
                   }
l.312 ...graphics{https://i.imgur.com/Ax3pp2A.png}
                                                  
? 
! Emergency stop.
<to be read again> 
                   }
l.312 ...graphics{https://i.imgur.com/Ax3pp2A.png}
                                                  
No pages of output.
Transcript written on notebook.log.

**Comment by jmbejara** [comment]
Hi Jacob. Sorry it took me so long to get to this. It looks like you are missing some LaTeX packages that this document needs to compile properly. Since you are using the MikTeX distribution (rather than TexLive), you might have some issues getting this to work since it appears to be using XeTeX. I have had issues with XeTeX and MikTeX working well together. In particular, I had issues with the `minted` package and some specific fonts in XeTeX. Here is a reference to some instructions that might help with your particular case: https://tex.stackexchange.com/questions/319150/miktex-xetex-def-package-installation

Also, I would make sure that you have your MiKTeX settins set to either automatically install packages for you or to set it to automatically prepare to install packages but to "ask you first". I don't know what MikTeX's default is but it might be set to *not* install packages on-the-fly.

Also, as a side note, I would actually recommend switching from MikTeX to TeXLive (uninstalling MikTeX in the process). I used MikTeX for years until I ran into some issues with XeTeX a few months ago. MiKTeX's philosophy is to provide a package manager to install packages when you need them. However, some packages sometimes don't work well with the package manager. TeXLive's philosophy is to provide every package ever in a single distribution that you download once when you install it. The idea is that they release a new version of TeXLive every year. What's nice about this is that  (1) it doesn't actually take up too much space to install TeXLive, (2) you don't actually have to worry about updating because LaTeX and its packages don't change much from year to year, and (3) you almost never have to worry about missing packages and the such.

**Comment by Jacob-Bishop** [comment]
Thanks for taking the time to look at this!

**Comment by jmbejara** [comment]
@Jacob-Bishop No problem! Did it fix the problem?
