### ISSUE TITLE
Folder of csv instead of xls file

### ISSUE THREAD

**Issue by vuphan95** [jmbejara/comp-econ-sp18#23]
In part 1 of HW 3 (creating_reading_writing), there's a part where we are supposed to download an xls file from https://www.kaggle.com/jpmiller/publicassistance/downloads/WICAgencies2014ytd.zip/2
However, when I download the zip file and extract it, I got a folder of csv files instead of one xls file.

**Comment by jmbejara** [comment]
You can find the link to the correct data here: https://github.com/jmbejara/comp-econ-sp18/issues/20

The link is here: https://www.kaggle.com/jpmiller/publicassistance/downloads/xls_files_all.zip/2
