### ISSUE TITLE
Interpretation of Chipotle Question 23

### ISSUE THREAD

**Issue by benpicker** [jmbejara/comp-econ-sp18#25]
The question states 
> 23. How many times did a Veggie Salad Bowl show up in an order?

Is this asking for the average number of veggie salad bowl requests per order? 

Suppose I have 4 orders. 
- Order 1: 
2 Veggie Salad Bowls
- Order 2: 
5 Veggie Salad Bowls
- Order 3: 
0 Veggie Salad Bowls 
- Order 4: 
0 Veggie Salad Bowls

What is the question asking for? 

For example, 
- Out of 4 orders, 7 Veggie Bowls were ordered. So average per order is 7/4. 
- Out of 4 orders, only two contained Veggie bowls.

**Comment by jmbejara** [comment]
Good question. I see the ambiguity. My intention was to ask "how many orders contained at least one Veggie salad bowl"

**Comment by jmbejara** [comment]
I've updated the HW to clarify this issue in this commit: 6e532d5ca1f0edb435e4212c2bbdb55073e99766
