### ISSUE TITLE
Creating Reading Writing Exercise 7

### ISSUE THREAD

**Issue by isabelalmazan** [jmbejara/comp-econ-sp18#28]
I'm having trouble opening the SQL. When I downloaded from the link, I get a zip file, and when I click on the zip file more zip files open, and when I click on any of those more zip files open, etc... Am I supposed to be able to load the data without touching the original zip file?

**Comment by jmbejara** [comment]
I can't quite figure out what's going wrong. When I download from the link, I get a zip file. Inside the zip file is the file `database.sqlite`. You should need to unzip the file before you can use it.

**Comment by jmbejara** [comment]
Maybe you could provide a screenshot of the issue? Or, you could stop by office hours tomorrow and Philip could take a look.

**Comment by isabelalmazan** [comment]
I'll stop by Philip's office hours tomorrow, but these are some screenshots of the new zip files that keep opening:
![screen shot 2018-04-22 at 6 36 15 pm](https://user-images.githubusercontent.com/37882403/39101223-515e0294-465c-11e8-8434-b9b7ec670fbd.png)
![screen shot 2018-04-22 at 6 36 42 pm](https://user-images.githubusercontent.com/37882403/39101224-554b6b6c-465c-11e8-8523-d97708ce6c8b.png)
![screen shot 2018-04-22 at 6 37 14 pm](https://user-images.githubusercontent.com/37882403/39101225-575204de-465c-11e8-8322-024062c1dd7f.png)

**Comment by jmbejara** [comment]
OK. Are you downloading from this link? https://www.kaggle.com/nolanbconaway/pitchfork-data/downloads/database.sqlite/1

**Comment by isabelalmazan** [comment]
Yes. Same issue.

**Comment by isabelalmazan** [comment]
I was thinking of trying to download to zip file on another computer tomorrow and send myself just the file in it, in case my computer is the problem. But I've already completed all of the other exercises and had no problem with any other zip file but this one.

Either way, I will go see Philip tomorrow to see if he can help in person.

**Comment by jmbejara** [comment]
OK.  Sounds good. Good luck!
