### ISSUE TITLE
Array Indexing with an Image

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#3]
For 2.1, is the code supposed to print out this massive color blob as the plot? I was wondering what I should be visualizing for this part.

![screen shot 2018-04-07 at 09 31 28](https://user-images.githubusercontent.com/37759075/38456146-a25018d0-3a46-11e8-8135-5b85d514f996.png)

**Comment by jmbejara** [comment]
You'll recognize the right plot when you see it. In this case you want to plot the matrix as an image. Use the following code to do it: `plt.imshow(face, cmap=plt.cm.gray)`.

I updated the HW to clarify this: https://github.com/jmbejara/comp-econ-sp18/commit/2b08872c747ff927a3843a36cb0b0dc4f10ce880

**Comment by afgong** [comment]
Should the raccoon look more or less clear when you apply the `np.sin(x/25)` function? My pictures go from quite clear to rather blurry. I also experienced the same blurriness with the 5 different values of n even though the pictures became progressively blurrier as n decreased, but it never started out again with the very clear raccoon picture at n=500. 

![screen shot 2018-04-08 at 13 33 25](https://user-images.githubusercontent.com/37759075/38471062-7f746b4a-3b31-11e8-9369-46adf7295399.png)

![screen shot 2018-04-08 at 13 33 38](https://user-images.githubusercontent.com/37759075/38471063-8321b98c-3b31-11e8-8a1e-66e2dca954a2.png)

**Comment by jmbejara** [comment]
Your result for `np.sin(x/25)` looks fine to me. I'm not sure I understand what the other issue is that you're describing. Perhaps it has something to do with the "gotcha" that we talked about in class? That is, watch out for the difference between deep copies and shallow copies of numpy arrays. 

```
a = np.array([0,1])
a
# Produces array([0, 1])

b = a
b[0] = 100
b
# Produces array([100,   1])

a
# Produces array([100,   1])
```
