### ISSUE TITLE
Post solutions to HW0

### ISSUE THREAD

**Issue by jmbejara** [jmbejara/comp-econ-sp18#30]

**Comment by afgong** [comment]
Have you been able to post HW4 / will we be tested on the material in HW4 on the midterm?

**Comment by jmbejara** [comment]
I haven't posted it yet. I'm hoping to have the assignment up tonight. The HW4 material will not be on the midterm.

**Comment by jmbejara** [comment]
Solutions to HW0 are available here: https://github.com/econ-21410-sp18/comp-econ-hw-jbejarano1/tree/master/hw-submit-00
