### ISSUE TITLE
Which samples to select for the IPUMS data?

### ISSUE THREAD

**Issue by vuphan95** [jmbejara/comp-econ-sp18#31]
I know which variables to select but forgot which samples to select. Right now I have selected only 18 ASEC samples for the years 2000-2017 (I deselect all the monthly samples). This in total is about 130 MB which seems wrong because the sample output of df.info() seems to suggest that the correct data has to be about 207 MB. Please remind me about which samples to select. Thank you so much!

**Comment by jmbejara** [comment]
Yep. Those look like the right samples! `DataFrame.info()` gives the memory usage. This will often be different from the total storage size of the file. It could often be larger.
