### ISSUE TITLE
GQ Variable

### ISSUE THREAD

**Issue by bariscangoc** [jmbejara/comp-econ-sp18#32]
Hi Jeremy,

I can't find variable GQ on the IPUMS CPS. I am searching with the search engine but I keep getting a message saying "Search Terms is too short (minimum is 3 characters)". Then I search for "Group Quarters status" but I still can't find the right variable.

Do you have any guesses on what is wrong?

Thanks,
Bariscan

**Comment by jmbejara** [comment]
That's strange. I found it like this: 

![image](https://user-images.githubusercontent.com/3770323/39401834-0db7e286-4b15-11e8-9de5-5685b533f363.png)

In any case, here's the link to the variable: https://cps.ipums.org/cps-action/variables/GQ#codes_section
