### ISSUE TITLE
HW0 Question 17

### ISSUE THREAD

**Issue by bariscangoc** [jmbejara/comp-econ-sp18#33]
Hi Jeremy,

I am trying to replicate what you did in q17, however it is giving me an error message as you can see in the attached screenshots. I was wondering whether I am doing something wrong, or the solution to the question is incorrect. 

Thanks!

<img width="948" alt="screenshot 2018-04-28 15 10 18" src="https://user-images.githubusercontent.com/37886280/39400460-759c5748-4af6-11e8-9b12-e32026c3bb3e.png">
<img width="515" alt="screenshot 2018-04-28 15 10 56" src="https://user-images.githubusercontent.com/37886280/39400461-79ca97e4-4af6-11e8-871b-615decb54ac3.png">

**Comment by jmbejara** [comment]
Yep. This is an error. Sorry about this. I'm fixing it now.

**Comment by jmbejara** [comment]
I've now corrected questions 3, 13, and 17 here: https://github.com/econ-21410-sp18/comp-econ-hw-jbejarano1/blob/master/hw-submit-00/python-basics-solutions.pdf
