### ISSUE TITLE
HW0 Q3

### ISSUE THREAD

**Issue by rrabines** [jmbejara/comp-econ-sp18#34]
```
def f():
    pass
print(type(f()))
```
This prints `<class 'NoneType'>`
rather than the marked option A.

Isn't this the case because the function f contains the pass function, which is a null operation and as the function is defined only with the null operation, it is categorized as a NoneType, an object with no value?

**Comment by jmbejara** [comment]
You're right. My apologies. Thanks for catching this. I will update the solutions now.

**Comment by jmbejara** [comment]
I've now corrected questions 3, 13, and 17 here: https://github.com/econ-21410-sp18/comp-econ-hw-jbejarano1/blob/master/hw-submit-00/python-basics-solutions.pdf
