### ISSUE TITLE
EDUC Variable

### ISSUE THREAD

**Issue by bariscangoc** [jmbejara/comp-econ-sp18#36]
Hi Jeremy,

For EDUC = 000, it defines as "NIU or no schooling". Should we consider it as NIU?

Thanks,
Bariscan

**Comment by jmbejara** [comment]
Hi Bariscan. Yes, I'm treating that as NIU. I'm labeling 999, 001, and 000 as missing.

**Comment by bariscangoc** [comment]
Thanks!
