### ISSUE TITLE
Q10: Strict inequalities vs weak inequalities

### ISSUE THREAD

**Issue by jmbejara** [jmbejara/comp-econ-sp18#42]
In Q10, I don't specifiy whether to use strict (<) or weak inequalities (<=). This could be the cause of some of the slight differences in results that some of you are having. For what it's worth, I'm using strict (<) inequalities.

**Comment by isabelalmazan** [comment]
Hi Jeremy, in Q11, we're using 'real_wage' to create the new 'median_wages' and 'ave_wages', but what are we basing 'employment' off of? The Boolean variable of whether they are in the labor force?

**Comment by jmbejara** [comment]
HI Isabel. Yes, that's correct. My intention was for you to use `in_labor_force` to measure employment. Also, as a note, when you do, be sure to take a weighted average of `in_labor_force`.
