### ISSUE TITLE
Visualization with Python HW

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#46]
What is the x-axis of your histogram in Q4?

**Comment by jmbejara** [comment]
It's `cty`. Thanks. I've updated the HW on github to add this clarification (and to fix the question numbering).

**Comment by isabelalmazan** [comment]
Does the order of the bars on the graphs in Q2 and Q3 have to be the same as yours?

**Comment by jmbejara** [comment]
Hi @isabelalmazan. Don't worry about the order so long as it's plotting the correct data.
