### ISSUE TITLE
Q3: Lognormal not defined at zero 

### ISSUE THREAD

**Issue by benpicker** [jmbejara/comp-econ-sp18#48]
Question 3 asks us to consider the values x∈(0,150000), but `linspace()` starts at the initial point given, so if I write `linspace(0,150000,100)` I will have a problem because lognorm isn't defined at x=0. 

What should I choose for my initial point?

**Comment by jmbejara** [comment]
I give the range x∈(0,150000) as opposed to x∈[0,150000]. Just choose a small number greater than zero to start from.
