### ISSUE TITLE
integration with scipy- normal distribution

### ISSUE THREAD

**Issue by alykhanb96** [jmbejara/comp-econ-sp18#5]
I'm stuck on this integration. I think I'm not using scipy correctly. Any one have any suggestions on a better approach

`result = scipy.integrate.quad(lambda x: (1.0/(2*3.1415*4)**1/2)*np.exp(-1*((x-1)**2)/2*4)), -2, 2)

SyntaxError: invalid syntax`

**Comment by alykhanb96** [comment]
revision- but i still have a problem
the actual code 
`result = scipy.integrate.quad(lambda x: ((1.0/(2*3.1415*4)**1/2)*np.exp(-1*((x-1)**2)/2*4)), -2, 2)
print(result)`
gets me the result

(0.024367361811287402, 4.612853002624809e-13)

but this is not the right answer i think

**Comment by Jacob-Bishop** [comment]
So I think your error is that you're multiplying 1*((x-1)**2)/2 times 4 instead of dividing -1*((x-1)**2) by (2*4). 
Also, as a side note I noticed both numpy and math modules have built-in approximations for pi, you don't have to approximate it yourself.

**Comment by jmbejara** [comment]
Ditto on Jacob's comments. Also watch out for order of operations on the exponentiation: `2**1/2` is not the same as `2**(1/2)`. Let me know if this helps!

Also, Jacob is referring to these:

```
import math
import numpy as np

math.pi
np.pi
```
