### ISSUE TITLE
Desired error not necessarily achieved due to precision loss

### ISSUE THREAD

**Issue by ethanmetzger** [jmbejara/comp-econ-sp18#50]
I keep on getting this message when I try to use the minimize function for question 11. Any idea what might be causing this?

**Comment by jmbejara** [comment]
@ethanmetzger I can't see the message. It looks like it didn't get attached.

**Comment by jmbejara** [comment]
Oh, I see now that the title is the message. This could be coming from a couple of things. It could be from logs of zero. Is the optimizer failing? You might check out the error referenced here: https://github.com/jmbejara/comp-econ-sp18/issues/53

That could help.
