### ISSUE TITLE
Loess Error

### ISSUE THREAD

**Issue by bariscangoc** [jmbejara/comp-econ-sp18#52]
Hi Jeremy,

I am getting this error " b'There are other near singularities as well. 0.65044\n'" after trying to use geom_smooth(method="loess").  Do you know what this means?

**Comment by jmbejara** [comment]
This issue is coming up because you need to use two different aesthetics when creating your plot. Take a look at the "mapping" keyword argument on "ggplot" and "geom_point". The smoothing should not be using the color aesthetic.

**Comment by bariscangoc** [comment]
It works now if I get rid of the color aesthetic. But the plot we need to have requires to use different color for different classes. How can I add color to this graph?

**Comment by jmbejara** [comment]
Use the "mapping" keyword argument to supply different aesthetics to different functions.
