### ISSUE TITLE
MLS and OLS q11

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#54]
I'm getting a floating point division by zero error (Runtime warning: invalid value encountered in double_scalars) when I try to minimize the negative log-likelihood. It seems to be triggered by very small sigmas. However, my answer from 12 suggests that the true sigma is close to zero, so I can't just eliminate these by setting bounds on the optimization. Any suggestions?

**Comment by jmbejara** [comment]
I'm getting runtime errors too, but my estimates and their standard errors match the OLS results.---including my estimates for sigma. I find that when I put bounds on the optimizer, the standard errors don't work. I'm not sure why. I'm using

```python
beta_0_init = 0
beta_1_init  = 0
beta_2_init  = 0
beta_3_init  = 0
sigma_init = 1
```
for my initial conditions.

**Comment by Jacob-Bishop** [comment]
So if I don't put bounds on the optimizer, I get x: array([ 0.e+00,  1.e-07,  1.e-01, -2.e+00,  4.e+00]). I don't get runtime errors if sigma is bounded to be >= 4. 

The precise error is:
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\optimize.py:643: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]

**Comment by jmbejara** [comment]
This is what my results look like:

![image](https://user-images.githubusercontent.com/3770323/39838857-22783e1c-53a0-11e8-835a-aeb6e29a5c6f.png)

![image](https://user-images.githubusercontent.com/3770323/39838874-2d88a724-53a0-11e8-8a7c-e90fc1fcd24d.png)

**Comment by jmbejara** [comment]
Here is some of my code:

```python
# get  a log likelihood for a regression using certain parameters and 
# certain data
def neg_log_lik_reg(params, *data):
    beta_0, beta_1, beta_2, beta_3, sigma = params
    sick, age, children, temp = data
    xvals = sick - beta_0 - beta_1 * age - beta_2 * children - beta_3 * temp
    log_lik_val = log_lik_norm(xvals, mu=0, sigma=sigma)
    return -log_lik_val
```

**Comment by Jacob-Bishop** [comment]
I'm doing ~ the same things, but my results aren't that nice. I sent you my code if you have a sec to look at it.

**Comment by Jacob-Bishop** [comment]
Fixed, I was missing a - sign.
