### ISSUE TITLE
Loading the data

### ISSUE THREAD

**Issue by ethanmetzger** [jmbejara/comp-econ-sp18#56]
<img width="252" alt="screen shot 2018-05-10 at 5 26 32 pm" src="https://user-images.githubusercontent.com/37875239/39897380-a0072c58-5477-11e8-979b-40d89fbd5e1d.png">

Do you know what's causing this problem? I'm just trying to load the data for HW6 using the exact code you've given.

**Comment by jmbejara** [comment]
Hi Ethan. I'm not sure why this happens. For me, it sometimes does this and if I try again, it sometimes works. You might as well just copy the actual file from the lectures directory to the directory where you're working on your HW. Or you could re-download the file directly. The file is located here: https://github.com/jmbejara/comp-econ-sp18/tree/master/lectures/5-10_Structural_IO_with_MLE

**Comment by rrabines** [comment]
Hi Jeremy!
The `BresnahanAndReiss1991_DATA.csv` file isn't in the 5-10_Structural_IO_with_MLE directory in lectures so we can't download it directly. Instead, there is `comp-econ-sp18/lectures/5-10_Structural_IO_with_MLE/bresnahan-reiss-1991-discussion.ipynb`, which states that its on the class GitHub page.
Is there another way to access the data, external to the class repository?

**Comment by jmbejara** [comment]
Hi Rosana. Sorry I missed that! It looks like I deleted it when I changed directory names yesterday. I've added back the data set to the folder. It should be there now. Thanks for the heads up!

https://github.com/jmbejara/comp-econ-sp18/blob/master/lectures/5-10_Structural_IO_with_MLE/BresnahanAndReiss1991_DATA.csv
