### ISSUE TITLE
HW 6 - clarifying the model

### ISSUE THREAD

**Issue by vuphan95** [jmbejara/comp-econ-sp18#57]
I have two questions:
1. What should I do with the inf values that result from taking log of 0? Should I exclude them from the sum?
2. Is the cdf that is used cdf of N(0, 1)? And can I use scipy.stats.norm.cdf() to calculate it?

**Comment by jmbejara** [comment]
1. Good question. I forgot to mention this. Any time you see a `-inf` for the log probability, change it to `-1e+08`.. That is, change it to `-100000000`.
  2. Yes. Use a N(0,1). 

 I'm updating the HW to include these instructions. Thanks!
