### ISSUE TITLE
Mean-Variance Question

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#6]
Intuitively, should the var-covar matrix be 5x5? Does the np.cov() method know to compute the means of each variable when producing the matrix?

The code that I currently have gives me a 500 x 500 matrix.

`Sigma = np.cov(prices)`
`Sigma`

EDIT: should I find the transpose of `prices` to obtain the variances? I did that instead, and now I have a 5x5 matrix. What is the intuition behind doing this?

`prices_trans = prices.T`
`prices_trans`
`Sigma = np.cov(prices_trans)`
`Sigma`

NVM I figured it out, sorry I just realized that the `'` means transpose

**Comment by jmbejara** [comment]
Also remember that you can use `np.cov(prices, rowvar=False)`. By default, `np.cov` assumes each row is a separate variable. The `prices` matrix uses each column as a separate variable.
