### ISSUE TITLE
q4- how to compare without alpha_4

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#61]
The original paper doesn't have an estimate for alpha_4. Should we just compare our theta vector with that entry removed to the original results?

**Comment by jmbejara** [comment]
The MLE result that I get is `alpha_4 = 0.0` . So I just assumed that the missing entry meant that their alpha_4 is zero too.

**Comment by afgong** [comment]
This is a question about Q3, but when you ask us to write out the correct NumPy array, do you want us to copy out the values from the table in the paper? Or can we just set `theta_br` equal to `results.x` from our MLE in Q2? Thank you!
