### ISSUE TITLE
Bresnahan Reiss Q2

### ISSUE THREAD

**Issue by isabelalmazan** [jmbejara/comp-econ-sp18#63]
Hi Jeremy,
I was able to get approximately the same log-likelihood (800001109) using theta0 and that in the paper (263.09) using the parameters from Table 4 in the paper. However when I tried running the optimization with bounds on the alphas only, I can't get my optimization's log-likelihood to converge to the provided result. 

I've tried (-0.01, None) and (-1, None) as bounds on the alphas - since the bounds are strict inequalities, and (None, None) on the rest - but neither of them seem to work, and the log-likelihood is stuck at ~205. Can you provide some guidance?

**Comment by jmbejara** [comment]
Hi @isabelalmazan . Sorry, the bounds should be on the alphas as well as the gammas (not including gamma_L). I am using tuples (0, np.inf) as the bounds on the alphas and gammas.  And, for what it's worth, I'm using the basic `scipy.optimize.minimize`.

Hope this helps!

**Comment by isabelalmazan** [comment]
I tried your bounds but am still way off:
![screen shot 2018-05-16 at 10 13 50 am](https://user-images.githubusercontent.com/37882403/40126021-f097d234-58f1-11e8-85d2-59bf12a6f530.png)
![screen shot 2018-05-16 at 10 14 04 am](https://user-images.githubusercontent.com/37882403/40126031-f5feca0c-58f1-11e8-8ac2-eccf5c79fba2.png)

The closest I've been able to get to the 263 is 261, which I got by "cheating" and using these extra specific bounds:
![screen shot 2018-05-16 at 10 15 41 am](https://user-images.githubusercontent.com/37882403/40126100-21e9bb36-58f2-11e8-8db7-f937fe1d94d5.png)

Even with the results from the cheating/ specific bounds minimization, my np.allclose function returns False at rtol=0.2, so I'm not really sure where I'm going wrong?

**Comment by jmbejara** [comment]
I think the best thing to do to diagnose the problem is to test a few values of the log-likelihood function. We should be getting the exact same numbers. Try the following random test:

```python
theta_test = np.array([1, 1, 1, 1, -1, -0.03,
0.01, -0.02, 0.8, 0.03, 0.1, 0, 0.1, 0.5,
1, 1, 1, 0.1, -1])

neg_log_like(theta_test)
```

When I run this, I get `324.2397071494959`

**Comment by isabelalmazan** [comment]
Ok, I get `269.9912536323145`. I'll go back into my log_like function and see where I made a mistake.
