### ISSUE TITLE
How to convert strings to float in R?

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#66]
Type.convert() seems to convert to numeric, but it doesn't have an argument to specify which kind of numeric value, and defaults to double.

**Comment by jmbejara** [comment]
To complete this exercise, I used a combination of the functions `gsub` and `as.numeric`.

**Comment by Jacob-Bishop** [comment]
The documentation I found (see below) seems to suggest as.numeric also produces doubles. Am I missing something?

https://www.rdocumentation.org/packages/base/versions/3.5.0/topics/numeric

**Comment by jmbejara** [comment]
I don't think that base R supports floats. The point of the assignment is to change from a string representation to a floating point number---whether that's a float or a double is unimportant. Plus, a Python `float` is not the same thing as a `float` vs `double` in a language like, say, C or C++.

**Comment by Jacob-Bishop** [comment]
Interesting, I didn't know that.

Does that hold for numpy/Pandas too, or does dtype=float give c types?

**Comment by jmbejara** [comment]
It's a little more complicated than that. For example, Numpy defines it's own data types. But Numpy is built in C. Python (the standard implementation) is also built in C. Some data types are platform dependent. (We once discussed in class how this might depend on whether your machine has a 32 or 64 bit architecture, etc.) 

I'm don't really know the details. You might check these out:

  - https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html
  - https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html
