### ISSUE TITLE
R packages tidyr and dplyr installation problems

### ISSUE THREAD

**Issue by alykhanb96** [jmbejara/comp-econ-sp18#67]
I'm trying to load and and make available to use the tidyr and dplyr package. but i get a set of errors.
My code is 
'''
install.packages(tidyr)
install.packages(dplyr)
library(tidyr)
library(dplyr)
''''
The error i get is this
'''
Error in install.packages : object 'dplyr' not found
> install.packages(tidyr)
Error in install.packages : object 'tidyr' not found
> install.packages(dplyr)
Error in install.packages : object 'dplyr' not found
> library(tidyr)
Error in library(tidyr) : there is no package called ‘tidyr’
> library(dplyr)
Error in library(dplyr) : there is no package called ‘dplyr’
'''
please help!

**Comment by jmbejara** [comment]
Hi Aly. Try putting the package names in quotation mark.

```R
install.packages('tidyr')
```
