### ISSUE TITLE
Different results depending on order of variables for covariance matrix?

### ISSUE THREAD

**Issue by benpicker** [jmbejara/comp-econ-sp18#72]
I tried both of these
 ```
cov = np.array([[1,0,0],
                [0,1,0.5],
                [0,0.5,1]])
df = pd.DataFrame(X, columns=['z1', 'u','epsilon'])
```

```
cov2 = np.array([[1,0,0.5],
                [0,1,0],
                [0.5,0,1]])
df = pd.DataFrame(X, columns=[ 'u','z1','epsilon'])
```
and found they yield different results. 

Shouldn't this not matter? Why would the order I put the variables influence the output?

**Comment by jmbejara** [comment]
This is a point that I hadn't thought of. It should indeed make a difference. I'm not sure how to best explain... The random seed sets the random number generators, but doesn't care about the ordering.
