### ISSUE TITLE
linear models regressions Q4

### ISSUE THREAD

**Issue by alykhanb96** [jmbejara/comp-econ-sp18#73]
for the 2SLS question I'm running 
''
iv = IV2SLS(dependent=df['y'],
            exog=df['x1'],
            endog=df['z1'],
            instruments=df['z1']).fit()
print(iv.summary)
'''
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
x1             1.7735     0.0626     28.310     0.0000      1.6507      1.8963
z1            -0.8525     0.1007 

which is not what i expected I thought i would get x1 to be 1

and for formula api i'm running
'''
import numpy as np
from linearmodels.iv import IV2SLS
formula = 'y ~ 1 +  [x1 ~ 1 + z1 + u] + epsilon'
mod =IV2SLS.from_formula(formula, simulate_data_ex1(N=50, seed=100)).fit()
'''
ValueError: instruments [exog instruments]  do not have full column rank
Can anyone help?

**Comment by jmbejara** [comment]
I'm not sure where the error is right off the bat. For one thing, `u` is unobserved and should not appear as a regressor or instrument in your formula.

**Comment by alykhanb96** [comment]
right...
I'm new code below  now 

from linearmodels.iv import IV2SLS
formula = 'y ~ 1 +  [x1 ~ 1 + z1]'
mod =IV2SLS.from_formula(formula, data = df).fit()
print(mod.summary)

right sorry, I'm running the above now
**ValueError: instruments [exog instruments]  do not have full column rank**
any advice on what i am doing wrong

**Comment by alykhanb96** [comment]
for the 2sls one I'm running:
'''
exog = sm.add_constant(df.x1)
endog = sm.add_constant(df.z1)
iv = IV2SLS(dependent=df['y'],
            exog=exog,
            endog=df['z1'],
            instruments=df['z1']).fit()
print(iv.summary)
'''
not getting the correct parameter for x1, how to i work in the constant that is supposed to go with z1?

**Comment by afgong** [comment]
reg_IV = (linearmodels
          .IV2SLS
          .from_formula('y ~ 1 + [x1 ~ z1]', data=df).fit())
reg_IV

I am running this code for Q4, but my x1 coefficient is 1.04. Would you know why it's 0.04 off even though it's 2SLS? I think my previous questions are correct, since I was able to return ~1.25 for the biased coefficient.

**Comment by jmbejara** [comment]
@alykhanb96 I'm not sure what you mean by not getting the right parameter? How off is it?

**Comment by jmbejara** [comment]
@afgong The IV procedure, as with any procedure, involves some luck. It's not going to be right on. Your Monte Carlo experiment should reveal that it is at least consistent as your sample sizes get larger.

**Comment by alykhanb96** [comment]
it turned out to be consistent, thanks again!

**Comment by afgong** [comment]
@jmbejara thanks for that intuition, it helped!

**Comment by afgong** [comment]
Isn't the bias in the Monte Carlo homework equal to 0.25? You have 1/2 as the answer to Q3, but 1/4 in Q6.

**Comment by jmbejara** [comment]
Oops. I didn't upload my up-to-date version. I will fix that soon. Thanks for pointing it out.

**Comment by jmbejara** [comment]
Sorry again about the error. I have now fixed the problem. See https://github.com/econ-21410-sp18/comp-econ-hw-jbejarano1/commit/ef595430ebfad87a6e22abdd4d4b816ee727aa51
