### ISSUE TITLE
Fixed Effects Q2

### ISSUE THREAD

**Issue by afgong** [jmbejara/comp-econ-sp18#74]
sfe = smf.mixedlm('fatalityrate ~ sb_usage + speed65 \
                                + speed70 + ba08 + drinkage21 \
                                + np.log(income) + age', 
                               data=seatbelts, 
                               groups=seatbelts['state'])

sfe2 = sfe.fit()
sfe2

I've copied the format of your code from the Fixed Effects Rosetta Stone notebook, but the code above, which I've written for Q2, is giving me this error: 

IndexError: index 556 is out of bounds for axis 1 with size 556

Any hint as to why this is the case? Thanks so much!

**Comment by afgong** [comment]
Would it perhaps have to do with missing data?

**Comment by jmbejara** [comment]
Hi Annabella,

I'm not sure what the error is here, but I would recommend using the `linearmodels` package. I give the example of using either `statsmodels` or `linearmodels` in my Rosetta stone notebook. But I think the `linearmodels` package is easier to use.

Check out the documentation here: https://bashtage.github.io/linearmodels/doc/panel/models.html#linearmodels.panel.model.PanelOLS
