### ISSUE TITLE
Graph on 3.4 (last question of HW)

### ISSUE THREAD

**Issue by isabelalmazan** [jmbejara/comp-econ-sp18#8]
Hi @jmbejara,

Are the instructions for the "(4) Use numpy.linspace to create a vector of N values equally spaced from -0.01 to 2" question supposed to be -0.01 to 0.02? (Did you mean 2% return rather than 200% return?)

Thanks!
-Isabel

**Comment by jmbejara** [comment]
Hi Isabel. You're correct in that it's silly to go that far out. But, yeah, 200% is what I wrote.
